import type { Site } from "@repo/db";

export const fakeSite = (patch: Partial<Site> = {}): Site => ({
  astroRepoUrl: null,
  authorBio: null,
  authorName: null,
  authorPhotoUrl: null,
  authorUrl: null,
  autoPublishEnabled: false,
  bucketRefillAt: null,
  bucketTarget: null,
  cadenceDays: null,
  categorySlugMap: {},
  createdAt: new Date(),
  defaultCategory: "sem-categoria",
  domain: "example.com",
  id: "site_1",
  imageStyle: null,
  isEnabled: true,
  language: "PT",
  lastAutoPublishedAt: null,
  moneySiteId: null,
  niches: [],
  topicHints: null,
  updatedAt: new Date(),
  vercelDeployHookUrl: null,
  vercelProjectName: null,
  ...patch,
});
